-- Add origin/destination fields to viagens for map functionality
ALTER TABLE viagens ADD COLUMN IF NOT EXISTS origem_cidade VARCHAR(100);
ALTER TABLE viagens ADD COLUMN IF NOT EXISTS origem_estado VARCHAR(2);
ALTER TABLE viagens ADD COLUMN IF NOT EXISTS destino_cidade VARCHAR(100);
ALTER TABLE viagens ADD COLUMN IF NOT EXISTS destino_estado VARCHAR(2);
ALTER TABLE viagens ADD COLUMN IF NOT EXISTS origem_lat DOUBLE PRECISION;
ALTER TABLE viagens ADD COLUMN IF NOT EXISTS origem_lng DOUBLE PRECISION;
ALTER TABLE viagens ADD COLUMN IF NOT EXISTS destino_lat DOUBLE PRECISION;
ALTER TABLE viagens ADD COLUMN IF NOT EXISTS destino_lng DOUBLE PRECISION;
